spring.application.name=todo-rest
server.port=${PORT:8080}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Documentacion OpenAPI / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
